###
POST http://localhost:5283/api/v1/accounts
Content-Type: application/json

{
  "name": "test 8",
  "username": "testnumber8",
  "password": "StrongPassw0rd!",
  "role": "Administrator"
}

###
GET http://localhost:5283/api/v1/accounts?pageNumber=1&pageSize=5
Content-Type: application/json
Accept: application/json
//Accept: text/csv

###
POST http://localhost:5283/api/v1/accounts/2c2f6cb9-2567-4460-9130-22608f9bae64/deposits
Content-Type: application/json

{
  "SenderAccId": "2c2f6cb9-2567-4460-9130-22608f9bae64",
  "Amount": 100
}
