###
POST http://localhost:5283/api/v1/accounts
Content-Type: application/json

{
  "name": "test 8",
  "username": "testnumber8",
  "password": "StrongPassw0rd!",
  "role": "Administrator"
}

###
GET http://localhost:5283/api/v1/accounts?pageNumber=1&pageSize=5
Content-Type: application/json
Accept: application/json
//Accept: text/csv

###
POST http://localhost:5283/api/v1/accounts/de51563a-3d0d-488e-9f99-ee250bb6fd2b/deposits
Content-Type: application/json

{
  "SenderAccId": "de51563a-3d0d-488e-9f99-ee250bb6fd2b",
  "Amount": 100
}
