@rootURL = http://localhost:5283

###
POST {{rootURL}}/api/Account
Accept: application/json
Content-Type: application/json

{
  "Name" : "jane"
}

###
GET {{rootURL}}/api/Account/b6a7199a-a150-4dfe-8886-925c186a1d90
Accept: application/json
Content-Type: application/json

###
POST {{rootURL}}/api/Account/b6a7199a-a150-4dfe-8886-925c186a1d90/deposits
Accept: application/json
Content-Type: application/json

{
  "Amount": "0"
}

###
POST {{rootURL}}/api/Account/b6a7199a-a150-4dfe-8886-925c186a1d90/withdrawals
Accept: application/json
Content-Type: application/json

{
  "Amount": "100"
}

###
POST {{rootURL}}/api/Account/transfers
Accept: application/json
Content-Type: application/json

{
  "SenderAccId": "b6a7199a-a150-4dfe-8886-925c186a1d90",
  "ReceiverAccId": "899d68c6-2dee-41e9-a757-23fd2cc32bd5",
  "Amount": "100"
}

###
GET {{rootURL}}/api/Account/b6a7199a-a150-4dfe-8886-925c186a1d90/balances?currency=RUB
Accept: application/json
Content-Type: application/json

